### ISSUE TITLE
Use constants for magic numbers

### ISSUE THREAD

**Issue by incredibleLeitman** [isaacGarcia92/NumberGuessing#3]
https://github.com/isaacGarcia92/NumberGuessing/blob/bb4d9cd1ca99230ede871715241e82ae44dc25ff/NumberGuessing/Program.cs#L9

https://github.com/isaacGarcia92/NumberGuessing/blob/bb4d9cd1ca99230ede871715241e82ae44dc25ff/NumberGuessing/Program.cs#L21

Instead of using a hardcoded "5" in your code (especially on multiple places) you should use constants

**Comment by isaacGarcia92** [comment]
I changed the hardcoded number to a constant.

**Comment by incredibleLeitman** [comment]
constants should be const or readonly, ALL_UPPERCASE and outside of your Main function 👆

**Comment by isaacGarcia92** [comment]
I added a constant NUM_OF_CHANCES so user chances can decrease in every input.

**Comment by incredibleLeitman** [comment]
then you should also use your constant to set the initial value of userChances 😏 
![image](https://user-images.githubusercontent.com/24638443/204143990-ad822e43-9c74-4b72-87e4-60c92b79c859.png)

**Comment by isaacGarcia92** [comment]
Came up with this approach:
![image](https://user-images.githubusercontent.com/118863715/204144349-a79b4da0-4865-4e61-a0ef-f854f11f9180.png)
